### ISSUE TITLE
'readline' module is deprecated

### ISSUE THREAD

**Issue by navii98** [indiajoe/WavelengthCalibrationTool#1]
'readline' package is one of the dependencies for this module, which is deprecated. In newer linux distributions it is creating dependency conflicts and this module does not install.
<s> 'readline' PyPI documentation suggests switching to 'gnureadline' which is a rename for the future versions of readline. </s>
Newer distributions should supposedly come with the newer version of 'readline'. My conda environment has readline 8.x installed but pip is not recognizing that and still trying to install readline 6.2 which will not install.

**Comment by anjasha** [comment]
readline is deprecated for macos m2 as well..the newer one is gnureadline.kindly consider this issue in the new installed version

**Comment by indiajoe** [comment]
Thanks for pointing this out. I am trying to see how to update the setup.py without breaking the backward compatibility on old machines. (This module is used in a few observatory servers where the systems will not be updated).
It looks like readline now comes as a built-in package in most python 3 installations. While switching to gnureadline will avoid the potential name conflict, I need to check about the backward compatibility and availability of gnureadline. Maybe there is a way to change in setup.py to make this readline installation optional on new systems.
Any thoughts and suggestions are welcome.

**Comment by anjasha** [comment]
Hi Joe,

So, as of now I changed all the import readline to import gnureadline. And
the pipeline installs..i hope this solves the problem for everyone as else.

Thanks and regards
Anjasha

**Comment by indiajoe** [comment]
I have decided to drop the readline install in setup.py since we have now more users in python 3.6+ than python 2.7 
This will hopefully solve the issue for most people.  Fixed in a5b05ddc453435f4de545f63f785e6cd58653229
For those using python 2.7 will have to explicitly install readline module.
